stages:
  - unit_test

before_script:
  - docker-php-ext-enable zip opcache
  - composer install

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
  - vendor/

# See https://blog.bitexpert.de/blog/running-matrix-builds-with-gitlab-ci/
.unit_test_template: &unit_test_definition
  stage: unit_test
  when: always
  script:
    - vendor/bin/phpunit

test:unit:php70:
  <<: *unit_test_definition
  image: tetraweb/php:7.0

test:unit:php71:
  <<: *unit_test_definition
  image: tetraweb/php:7.1
